/*******************************************************************************
  kb.h — MPLAB ML-compatible knowledge-pack public API for the AK gesture demo.

  The API surface matches what MPLAB Machine Learning Development Suite emits
  for a Source-Format knowledge pack, so application/sml_recognition_run.c and
  application/sml_output.c compile unchanged against this hand-crafted pack.

  Implementation lives in mplabml/src/kb.c; classifier constants live in
  mplabml/inc/kp_model_data.h (regenerated by tools/train_kp.py).
*******************************************************************************/
#ifndef KB_H
#define KB_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Max size of a raw feature vector printed by kb_sprint_model_result — the
 * real pack has 8 features but application code allocates buffers by
 * MAX_VECTOR_SIZE so we leave headroom for a future retrain. */
#define MAX_VECTOR_SIZE          16
#define MAX_NUMBER_OF_MODELS     1

/* Class IDs emitted by kb_run_model (match knowledge-pack/model.json). */
#define KB_CLASS_UNKNOWN         0
#define KB_CLASS_EIGHT           1   /* not trained — reserved */
#define KB_CLASS_IDLE            2
#define KB_CLASS_UP_DOWN         3
#define KB_CLASS_WAVE            4
#define KB_CLASS_WHEEL           5

/* Called once at startup before the first kb_run_model call. */
void            kb_model_init(void);

/* Feed one sensor frame (data points to num_sensors int16 values; the pack
 * uses the first 3 as accel x/y/z). Returns:
 *    >= 0 : classification id (see KB_CLASS_* above)
 *    <  0 : window not yet full, no classification this call */
int32_t         kb_run_model(int16_t *data, int32_t num_sensors, int32_t model_index);

/* Reset per-model state. Currently a no-op — the window auto-clears after
 * each classification. */
void            kb_reset_model(int32_t model_index);

/* Return a stable 16-byte UUID identifying the loaded model. Regenerated
 * whenever the trainer produces new centroids. */
const uint8_t * kb_get_model_uuid_ptr(int32_t model_index);

/* Emit a JSON-formatted string describing the last classification into buf.
 * Returns the number of characters written. buf must be >= 256 bytes. */
int             kb_sprint_model_result(uint16_t model_index, char *buf,
                                       int include_feature_vector,
                                       int include_debug,
                                       int newline);

#ifdef __cplusplus
}
#endif

#endif /* KB_H */
