/*******************************************************************************
  Auto-generated by tools/train_kp.py — DO NOT EDIT BY HAND.

  Baked-in class centroids, per-feature MAD scale, and per-class rejection
  thresholds for the AK gesture knowledge pack.  Regenerate by running:
      python tools/train_kp.py
*******************************************************************************/
#ifndef KP_MODEL_DATA_H
#define KP_MODEL_DATA_H

#include <stdint.h>

#define KP_NUM_FEATURES   8
#define KP_NUM_CLASSES    4
#define KP_WINDOW_SIZE    100
#define KP_LPF_LEN        10
#define KP_CLASS_UNKNOWN  0

static const int32_t kp_class_ids[KP_NUM_CLASSES] = { 1, 2, 3, 4 };

static const char * const kp_class_names[KP_NUM_CLASSES] = {
    "IDLE",
    "UP-DOWN",
    "WAVE",
    "WHEEL",
};

static const int32_t kp_centroids[KP_NUM_CLASSES][KP_NUM_FEATURES] = {
    {       -292,       -370,        324,         -5,        -40,        -35,          2,         27 },
    {        970,      25754,  162475415,     -25132,      -7013,      18119,          1,      35583 },
    {      20288,      20792,  124667924,      30743,      37141,       6398,          0,      26883 },
    {       4890,      20406,   39318321,       -987,       8760,       9747,          1,      18388 },
};

static const int32_t kp_scale[KP_NUM_FEATURES] = {
          3249,       3167,   52090230,       8528,       7172,       7057,          1,      12157
};

static const int32_t kp_reject_threshold[KP_NUM_CLASSES] = {
          1541,       6699,      12286,       6305
};

static const uint8_t kp_model_uuid[16] = {
    0xef, 0xf4, 0x7a, 0x39, 0xc2, 0xe4, 0x02, 0xf7, 0x39, 0x02, 0xea, 0x56, 0xe8, 0xf7, 0x70, 0xaa
};

#endif /* KP_MODEL_DATA_H */
