/*******************************************************************************
  Hand-crafted MPLAB ML-compatible knowledge pack for the dsPIC33AK1024MPS614
  gesture demo.  Implements the same 8-feature pipeline as the CK reference
  (see knowledge-pack/model.json) but uses a nearest-centroid classifier with
  a Z-normalised L1 distance metric and per-class rejection thresholds.

  All constants (class centroids, per-feature MAD scales, rejection thresholds,
  UUID) are auto-generated by tools/train_kp.py from the CSVs in dataset/.

  Feature layout (must match training script and CK model.json order):
    [0] x75Percentile           75th percentile of x
    [1] y75Percentile           75th percentile of y
    [2] yVariance               population variance of y
    [3] xxyy_cross_p2p_diff     P2P(x) - P2P(y)
    [4] xxzz_cross_p2p_diff     P2P(x) - P2P(z)
    [5] yyzz_cross_p2p_diff     P2P(y) - P2P(z)
    [6] xxyyzz_cross_max_col    argmax P2P over {x,y,z}
    [7] yMaxP2PGlobalDC         P2P of moving-avg(y, len=KP_LPF_LEN)

  Runtime contract (kb.h):
    - kb_run_model() is called once per sensor frame (100 Hz).
    - When a full KP_WINDOW_SIZE-sample window is accumulated, features are
      computed, classification runs, and the returned class ID is one of
      {0=Unknown, 2=IDLE, 3=UP-DOWN, 4=WAVE, 5=WHEEL}.
    - Between windows the function returns -1.
*******************************************************************************/
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "../inc/kb.h"
#include "../inc/kp_model_data.h"

/* ------------------------------------------------------------------------- *
 *  Window buffer state
 * ------------------------------------------------------------------------- */
static int16_t  g_win_x[KP_WINDOW_SIZE];
static int16_t  g_win_y[KP_WINDOW_SIZE];
static int16_t  g_win_z[KP_WINDOW_SIZE];
static uint16_t g_win_fill;

/* Last-classification cache (for kb_sprint_model_result) */
static int32_t  g_last_class = KP_CLASS_UNKNOWN;
static int32_t  g_last_features[KP_NUM_FEATURES];
static int32_t  g_last_distance;
static uint8_t  g_last_matched_slot;

/* ------------------------------------------------------------------------- *
 *  Small helpers
 * ------------------------------------------------------------------------- */
static int cmp_i16(const void *a, const void *b)
{
    int16_t va = *(const int16_t *)a;
    int16_t vb = *(const int16_t *)b;
    return (va > vb) - (va < vb);
}

static int32_t percentile_75_i16(const int16_t *col)
{
    int16_t tmp[KP_WINDOW_SIZE];
    memcpy(tmp, col, sizeof(tmp));
    qsort(tmp, KP_WINDOW_SIZE, sizeof(int16_t), cmp_i16);
    /* Same integer index formula the trainer uses: int(0.75 * (N-1)) */
    uint16_t idx = (uint16_t)((3u * (KP_WINDOW_SIZE - 1u)) / 4u);
    return (int32_t)tmp[idx];
}

static int32_t p2p_i16(const int16_t *col)
{
    int16_t mn = col[0];
    int16_t mx = col[0];
    for (uint16_t i = 1; i < KP_WINDOW_SIZE; i++) {
        if (col[i] < mn) mn = col[i];
        if (col[i] > mx) mx = col[i];
    }
    return (int32_t)mx - (int32_t)mn;
}

static int32_t variance_i16(const int16_t *col)
{
    /* Sum in int32 (fits: 100 * 32767 ~= 3.3e6). */
    int32_t sum = 0;
    for (uint16_t i = 0; i < KP_WINDOW_SIZE; i++) {
        sum += (int32_t)col[i];
    }
    int32_t mean = sum / (int32_t)KP_WINDOW_SIZE;

    /* Sum of squared deviations needs int64 (100 * 65535^2 ~= 4.3e11). */
    int64_t acc = 0;
    for (uint16_t i = 0; i < KP_WINDOW_SIZE; i++) {
        int32_t d = (int32_t)col[i] - mean;
        acc += (int64_t)d * (int64_t)d;
    }
    return (int32_t)(acc / (int64_t)KP_WINDOW_SIZE);
}

static int32_t max_col_p2p_index(int32_t px, int32_t py, int32_t pz)
{
    /* Match numpy.argmax: returns lowest index on ties. */
    if (px >= py && px >= pz) return 0;
    if (py >= pz)             return 1;
    return 2;
}

static int32_t lpf_p2p_y(const int16_t *y)
{
    /* Integer boxcar filter (running sum) with length KP_LPF_LEN, then P2P. */
    if (KP_WINDOW_SIZE < KP_LPF_LEN) return p2p_i16(y);

    int32_t s = 0;
    for (uint16_t i = 0; i < KP_LPF_LEN; i++) s += (int32_t)y[i];

    int32_t first = s / (int32_t)KP_LPF_LEN;
    int32_t mn = first, mx = first;

    const uint16_t n_out = KP_WINDOW_SIZE - KP_LPF_LEN + 1u;
    for (uint16_t i = 1; i < n_out; i++) {
        s += (int32_t)y[i + KP_LPF_LEN - 1u] - (int32_t)y[i - 1u];
        int32_t v = s / (int32_t)KP_LPF_LEN;
        if (v < mn) mn = v;
        if (v > mx) mx = v;
    }
    return mx - mn;
}

/* ------------------------------------------------------------------------- *
 *  Feature extraction over the current window
 * ------------------------------------------------------------------------- */
static void extract_features(int32_t *feat)
{
    int32_t px = p2p_i16(g_win_x);
    int32_t py = p2p_i16(g_win_y);
    int32_t pz = p2p_i16(g_win_z);

    feat[0] = percentile_75_i16(g_win_x);
    feat[1] = percentile_75_i16(g_win_y);
    feat[2] = variance_i16   (g_win_y);
    feat[3] = px - py;
    feat[4] = px - pz;
    feat[5] = py - pz;
    feat[6] = max_col_p2p_index(px, py, pz);
    feat[7] = lpf_p2p_y      (g_win_y);
}

/* ------------------------------------------------------------------------- *
 *  Nearest-centroid classification (Z-normalised L1 distance)
 * ------------------------------------------------------------------------- */
static int32_t classify(const int32_t *feat, int32_t *out_dist, uint8_t *out_slot)
{
    int32_t best_slot = -1;
    int64_t best_dist = INT64_MAX;

    for (uint8_t c = 0; c < KP_NUM_CLASSES; c++) {
        int64_t d = 0;
        for (uint8_t k = 0; k < KP_NUM_FEATURES; k++) {
            int64_t diff = (int64_t)feat[k] - (int64_t)kp_centroids[c][k];
            if (diff < 0) diff = -diff;
            /* Match trainer: |diff| * 1000 / scale[k]  (integer floor toward 0
             * for the non-negative operands used here — Python // and C /
             * agree for non-negatives). */
            d += (diff * (int64_t)1000) / (int64_t)kp_scale[k];
        }
        if (d < best_dist) {
            best_dist = d;
            best_slot = (int32_t)c;
        }
    }

    *out_dist = (best_dist > (int64_t)INT32_MAX) ? INT32_MAX : (int32_t)best_dist;
    *out_slot = (uint8_t)best_slot;

    /* Apply per-class rejection threshold — 5x the trained value to absorb
     * board-to-board mounting differences (training data came from the CK
     * reference board; AK Curiosity + Click may present a different rest
     * gravity vector, feature scale, etc.). Retraining from AK-captured
     * CSVs would let us tighten this back down to 1x. */
    if (best_dist > (int64_t)kp_reject_threshold[best_slot] * 5) {
        return KP_CLASS_UNKNOWN;
    }
    return kp_class_ids[best_slot];
}

/* ------------------------------------------------------------------------- *
 *  Public API (kb.h)
 * ------------------------------------------------------------------------- */
void kb_model_init(void)
{
    g_win_fill = 0;
    g_last_class = KP_CLASS_UNKNOWN;
    g_last_distance = 0;
    g_last_matched_slot = 0;
    memset(g_last_features, 0, sizeof(g_last_features));
}

int32_t kb_run_model(int16_t *data, int32_t num_sensors, int32_t model_index)
{
    (void)model_index;
    if (data == NULL || num_sensors < 3) return -1;

    /* Firmware feeds accel-only 3 channels (SNSR_USE_GYRO=false). If gyro is
     * ever re-enabled the first 3 channels are still accel — we only look at
     * those. */
    g_win_x[g_win_fill] = data[0];
    g_win_y[g_win_fill] = data[1];
    g_win_z[g_win_fill] = data[2];
    g_win_fill++;

    if (g_win_fill < KP_WINDOW_SIZE) return -1;

    /* Window full — run inference. Non-overlapping (delta=window_size). */
    g_win_fill = 0;

    extract_features(g_last_features);
    g_last_class = classify(g_last_features, &g_last_distance, &g_last_matched_slot);
    return g_last_class;
}

void kb_reset_model(int32_t model_index)
{
    (void)model_index;
    /* Window is already cleared inside kb_run_model after a classification.
     * Nothing else to reset. */
}

const uint8_t *kb_get_model_uuid_ptr(int32_t model_index)
{
    (void)model_index;
    return kp_model_uuid;
}

int kb_sprint_model_result(uint16_t model_index, char *buf,
                           int include_feature_vector,
                           int include_debug,
                           int newline)
{
    int written = 0;
    const char *cname = "UNKNOWN";
    if (g_last_class != KP_CLASS_UNKNOWN && g_last_matched_slot < KP_NUM_CLASSES) {
        cname = kp_class_names[g_last_matched_slot];
    }

    written += snprintf(buf, 256,
                        "{\"ModelNumber\":%u,\"Classification\":%ld,\"Label\":\"%s\"",
                        (unsigned)model_index, (long)g_last_class, cname);

    if (include_debug) {
        written += snprintf(&buf[written], 256 - written,
                            ",\"Distance\":%ld,\"Threshold\":%ld",
                            (long)g_last_distance,
                            (long)kp_reject_threshold[g_last_matched_slot]);
    }
    if (include_feature_vector) {
        written += snprintf(&buf[written], 256 - written,
                            ",\"FeatureLength\":%d,\"FeatureVector\":[",
                            KP_NUM_FEATURES);
        for (uint8_t k = 0; k < KP_NUM_FEATURES; k++) {
            written += snprintf(&buf[written], 256 - written,
                                (k == KP_NUM_FEATURES - 1u) ? "%ld" : "%ld,",
                                (long)g_last_features[k]);
        }
        written += snprintf(&buf[written], 256 - written, "]");
    }
    written += snprintf(&buf[written], 256 - written, "}%s",
                        newline ? "\r\n" : "");
    return written;
}
